---
name: Caddy Standalone Linux
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.13-nogil', '3.14']
    env:
      GOEXPERIMENT: cgocheck2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python and build Caddy
        if: matrix.python-version != '3.13-nogil'
        run: |
          bash scripts/setup-python-and-build.sh \
            --python-version ${{ matrix.python-version }} \
            --build-caddy \
            --caddy-snake-path ../.. \
            --working-dir cmd/embed
      - name: Set up Python (nogil) and build Caddy
        if: matrix.python-version == '3.13-nogil'
        run: |
          bash scripts/setup-python-and-build.sh \
            --python-version ${{ matrix.python-version }} \
            --build-caddy \
            --caddy-snake-path ../.. \
            --working-dir cmd/embed
      - name: Retrive python build standalone
        if: matrix.python-version != '3.13-nogil'
        working-directory: cmd/embed
        run: |
          python3 pybs.py latest --python-version ${{ matrix.python-version }} --architecture x86_64_v2-unknown-linux-gnu --build-config pgo+lto --content-type install_only_stripped
          mv cpython-*.tar.gz python-standalone.tar.gz
          go build main.go
          mv main caddy
      - name: Retrive python build standalone (nogil)
        if: matrix.python-version == '3.13-nogil'
        working-directory: cmd/embed
        run: |
          python3 pybs.py latest --python-version 3.13 --architecture x86_64_v2-unknown-linux-gnu --build-config freethreaded+pgo+lto --content-type full
          tar -xf cpython-*.tar.zst
          mv python/install .
          rm -rf python
          mv install python
          tar -czf python-standalone.tar.gz python
          go build main.go
          mv main caddy
      - name: Upload caddy standalone
        uses: actions/upload-artifact@v4
        with:
          name: caddy-standalone-${{ matrix.python-version }}-x86_64_v2-unknown-linux-gnu
          path: |
            cmd/embed/caddy
      - name: Package caddy standalone
        if: github.event_name == 'release'
        run: |
          tar -czf caddy-standalone-${{ matrix.python-version }}-x86_64_v2-unknown-linux-gnu.tar.gz cmd/embed/caddy
      - name: Upload to release
        if: github.event_name == 'release'
        run: |
          gh release upload ${{ github.event.release.tag_name }} caddy-standalone-${{ matrix.python-version }}-x86_64_v2-unknown-linux-gnu.tar.gz --repo ${{ github.repository }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  