---
name: Caddy Standalone Linux
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.13-nogil', '3.14']
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: false
      - name: Install Xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build the server
        working-directory: cmd/embed
        run: CGO_ENABLED=0 xcaddy build --with github.com/mliezun/caddy-snake=../..
      - name: Choose architecture
        id: choose-arch
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04-arm" ]; then
            PYBS_ARCH=aarch64-unknown-linux-gnu
          else
            PYBS_ARCH=x86_64_v2-unknown-linux-gnu
          fi
          echo "PYBS_ARCH=${PYBS_ARCH}" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Retrieve python build standalone
        if: matrix.python-version != '3.13-nogil'
        working-directory: cmd/embed
        run: |
          python3 pybs.py latest --python-version ${{ matrix.python-version }} --architecture ${{ steps.choose-arch.outputs.PYBS_ARCH }} --build-config pgo+lto --content-type install_only_stripped
          mv cpython-*.tar.gz python-standalone.tar.gz
          go build main.go
          mv main caddy
      - name: Retrieve python build standalone (nogil)
        if: matrix.python-version == '3.13-nogil'
        working-directory: cmd/embed
        run: |
          python3 pybs.py latest --python-version 3.13 --architecture ${{ steps.choose-arch.outputs.PYBS_ARCH }} --build-config freethreaded+pgo+lto --content-type full
          tar -xf cpython-*.tar.zst
          mv python/install .
          rm -rf python
          mv install python
          tar -czf python-standalone.tar.gz python
          go build main.go
          mv main caddy
      - name: Upload caddy standalone
        uses: actions/upload-artifact@v4
        with:
          name: caddy-standalone-${{ matrix.python-version }}-${{ steps.choose-arch.outputs.PYBS_ARCH }}
          path: |
            cmd/embed/caddy
      - name: Package caddy standalone
        if: github.event_name == 'release'
        run: |
          tar -czf caddy-standalone-${{ matrix.python-version }}-${{ steps.choose-arch.outputs.PYBS_ARCH }}.tar.gz cmd/embed/caddy
      - name: Upload to release
        if: github.event_name == 'release'
        run: |
          gh release upload ${{ github.event.release.tag_name }} caddy-standalone-${{ matrix.python-version }}-${{ steps.choose-arch.outputs.PYBS_ARCH }}.tar.gz --repo ${{ github.repository }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
